import { supabaseAdmin } from './client';
import type { Company, Section, Job, Theme } from '../types';

/**
 * Seed sample companies data into the database
 */
export async function seedDatabase(companies: Company[]) {
  try {
    const results = [];

    for (const company of companies) {
      // Insert company
      const { data, error } = await supabaseAdmin
        .from('companies')
        .insert({
          slug: company.slug,
          name: company.name || null,
          theme: company.theme || {},
          sections: company.sections || [],
          jobs: company.jobs || [],
        })
        .select()
        .single();

      if (error) {
        // If company exists, update it
        if (error.code === '23505') {
          const { data: updated, error: updateError } = await supabaseAdmin
            .from('companies')
            .update({
              name: company.name || null,
              theme: company.theme || {},
              sections: company.sections || [],
              jobs: company.jobs || [],
            })
            .eq('slug', company.slug)
            .select()
            .single();

          if (updateError) {
            console.error(`Error updating company ${company.slug}:`, updateError);
            results.push({ slug: company.slug, status: 'error', error: updateError.message });
          } else {
            results.push({ slug: company.slug, status: 'updated', data: updated });
          }
        } else {
          console.error(`Error inserting company ${company.slug}:`, error);
          results.push({ slug: company.slug, status: 'error', error: error.message });
        }
      } else {
        results.push({ slug: company.slug, status: 'created', data });
      }
    }

    return {
      success: true,
      results,
      total: companies.length,
      created: results.filter(r => r.status === 'created').length,
      updated: results.filter(r => r.status === 'updated').length,
      errors: results.filter(r => r.status === 'error').length,
    };
  } catch (error) {
    console.error('Seed error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Helper function to create sample company data
 */
export function createSampleCompany(
  slug: string,
  name: string,
  theme?: Theme,
  sections?: Section[],
  jobs?: Job[]
): Company {
  return {
    id: '', // Will be generated by database
    slug,
    name,
    theme: theme || {
      primary: '#3b82f6',
      secondary: '#8b5cf6',
      accent: '#10b981',
    },
    sections: sections || [
      {
        id: '1',
        type: 'about',
        title: 'About Us',
        content: 'We are a growing company...',
        order: 0,
        is_visible: true,
      },
    ],
    jobs: jobs || [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
}
